backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "homepage"
    label: "Página Inicial"
    files:
      - file: "index.html"
        label: "Página principal"
        name: "index"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "body", widget: "text" }

